# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 751aa5b7a26f51d98c551abcaa3cbe55836349408b314f01ae04ed70b0365c75a33a030ab7d6e99ad556721efa7c8acc655b9366aeb967838e23959b2e32ac73

test:
  secret_key_base: 32d2e08b5ba40d9e1866b735ca9acd409ffb05bc478db1e8b6859e5109015fa182d8e4a4f4b754a2dc4291d60782914ff3dd43485256a1511395e3ad76ab9f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
